// let response = sample()
// let response = await sample()

// async function sample(){
//     //db call

//     let q1 = query1()
//     let q2 = query2()
//     let q3 = query3()

// }

// const obj = {
//   a: 1,
//   b: 2,
// };

// const obj1 = obj;

// obj1.a = 3;

// console.log(obj); //{a:3, b:2}

// const obj = {
//   a: 1,
//   b: 2,
//   c: {
//     x: 3,
//     z: 4,
//   },
// };

// // const obj1 = obj
// const obj1 = {...obj, c:{...obj.c}};

// obj1.c.x = 5;
// obj1.a = 5;

// console.log(obj); // {a:1, b:2, c:{x:3, z:4}}

// const arr = [1, 2, 3];

// console.log(arr instanceof Array);
// console.log(arr instanceof Object);
// console.log(arr instanceof Number);

// function foo() {
// //   let a = (b = 0);
//     let a=0
//   a++;
//   return a;
// }

// foo();
// console.log(typeof a);
// console.log(typeof b);

// Assume you have three tables: customers, orders and order_items
// Table structure for 'orders':
 
// Table structure for 'customers':
// CREATE TABLE customers(
//   customer_id INT PRIMARY KEY,
//   customer_name VARCHAR(255)
// );
 
// CREATE TABLE orders(
//   order_id INT PRIMARY KEY,
//   customer_id INT,
//   order_date DATE
//   FOREIGN KEY(customer_id) REFERENCES customers(customer_id)
// );
 
// Table structure for 'order_items':
// CREATE TABLE order_items(
//   order_item_id INT PRIMARY KEY,
//   order_id INT,
//   product_id INT,
//   quantity INT,
//   price DECIMAL(10, 2),
//   FOREIGN KEY(order_id) REFERENCES orders(order_id)
// );
 
// Problem statement:
 
// Write a SQL query to find the total revenue generated by each customer
// in the year 2022. Include the customer's name, total revenue, and the
// number of orders placed by each customer in the specified year.
// Display the results in descending order of total revenue.

// select c.customer_name from customer c, oi.price, o.order_id join orders o on o.customer_id = c.customer_id join order_items oi on oi.order_id = o.order_id sum oi.price




